property:
  static: "Hello as property"
  dynamic: ${random.uuid}
  date: "2019-12-11"
  validatedNumber: 3

spring:
  profiles:
    active:
      - development #development or production
  boot:
    admin:
      url: http://localhost:8081
management:
  security:
    enabled: false